/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Inicio;
import conexionsql.CConexion;
import javax.swing.JOptionPane;
/**
 *
 * @author Axel
 */
public class frmRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRegistro
     */
    public frmRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaneRegistrodeusuario = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        cbtipoUsuario = new javax.swing.JComboBox<>();
        btnregistrarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);
        setMaximizable(true);
        setTitle("Registro de Usuarios\n");
        setOpaque(true);

        jpaneRegistrodeusuario.setBackground(new java.awt.Color(204, 204, 204));
        jpaneRegistrodeusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Usuarios"));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRES:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N
        txtNombre.setCaretColor(new java.awt.Color(51, 51, 51));
        txtNombre.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APELLIDOS:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        txtDNI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        cbtipoUsuario.setBackground(new java.awt.Color(242, 242, 242));
        cbtipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Directora", " " }));
        cbtipoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N
        cbtipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoUsuarioActionPerformed(evt);
            }
        });

        btnregistrarUsuario.setBackground(new java.awt.Color(255, 204, 204));
        btnregistrarUsuario.setText("Registrar usuario");
        btnregistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicio/72648.png"))); // NOI18N

        txtPass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        javax.swing.GroupLayout jpaneRegistrodeusuarioLayout = new javax.swing.GroupLayout(jpaneRegistrodeusuario);
        jpaneRegistrodeusuario.setLayout(jpaneRegistrodeusuarioLayout);
        jpaneRegistrodeusuarioLayout.setHorizontalGroup(
            jpaneRegistrodeusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneRegistrodeusuarioLayout.createSequentialGroup()
                .addGroup(jpaneRegistrodeusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaneRegistrodeusuarioLayout.createSequentialGroup()
                        .addGroup(jpaneRegistrodeusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaneRegistrodeusuarioLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(cbtipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpaneRegistrodeusuarioLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnregistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneRegistrodeusuarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpaneRegistrodeusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                            .addComponent(txtApellido)
                            .addComponent(txtNombre))
                        .addGap(22, 22, 22)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jpaneRegistrodeusuarioLayout.setVerticalGroup(
            jpaneRegistrodeusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneRegistrodeusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaneRegistrodeusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaneRegistrodeusuarioLayout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbtipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpaneRegistrodeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpaneRegistrodeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoUsuarioActionPerformed

    private void btnregistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarUsuarioActionPerformed
         String Nombre = txtNombre.getText();
    String Apellido = txtApellido.getText();
    String Contrasena = new String(txtPass.getPassword());
    String dni = txtDNI.getText();
    String tipoUsuario = cbtipoUsuario.getSelectedItem().toString();

    if (Nombre.isEmpty() || Apellido.isEmpty() || Contrasena.isEmpty() || dni.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        return;
    }

    if (!dni.matches("\\d{8}")) {
        JOptionPane.showMessageDialog(this, "El DNI debe tener exactamente 8 dígitos numéricos.");
        return;
    }

    CConexion objConexion = new CConexion();
    objConexion.RegistroUsuario(Nombre, Apellido, Contrasena, dni, tipoUsuario);

    txtNombre.setText("");
    txtApellido.setText("");
    txtPass.setText("");
    txtDNI.setText("");
    cbtipoUsuario.setSelectedIndex(0);

    System.exit(0);

    }//GEN-LAST:event_btnregistrarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrarUsuario;
    private javax.swing.JComboBox<String> cbtipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpaneRegistrodeusuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
