/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Inicio;

/**
 *
 * @author aaron
 */
public class MantenimientoDePersonal extends javax.swing.JInternalFrame {

    /**
     * Creates new form MantenimientoDePersonal
     */
    public MantenimientoDePersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtNombres = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtCorreo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cbCargo = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        lblherramientas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimientopesonal = new javax.swing.JTable();
        TxtAsistencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento de Pesonal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        TxtNombres.setBackground(new java.awt.Color(51, 51, 51));
        TxtNombres.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.add(TxtNombres);
        TxtNombres.setBounds(53, 76, 282, 38);

        txtDNI.setBackground(new java.awt.Color(51, 51, 51));
        txtDNI.setForeground(new java.awt.Color(255, 255, 255));
        txtDNI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.add(txtDNI);
        txtDNI.setBounds(650, 70, 280, 40);

        TxtDireccion.setBackground(new java.awt.Color(51, 51, 51));
        TxtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        TxtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIRECCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.add(TxtDireccion);
        TxtDireccion.setBounds(50, 160, 282, 45);

        TxtCorreo.setBackground(new java.awt.Color(51, 51, 51));
        TxtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        TxtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CORREO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.add(TxtCorreo);
        TxtCorreo.setBounds(650, 160, 282, 42);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimagenes/4202259.jpg"))); // NOI18N
        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(70, 390, 160, 60);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimagenes/3488813.jpg"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(240, 390, 160, 60);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimagenes/1251053.jpg"))); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(410, 390, 160, 60);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimagenes/3022155.jpg"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        jPanel1.add(btnLimpiar);
        btnLimpiar.setBounds(580, 390, 160, 60);

        cbCargo.setBackground(new java.awt.Color(51, 51, 51));
        cbCargo.setForeground(new java.awt.Color(255, 255, 255));
        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor", "Auxiliar" }));
        cbCargo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CARGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        cbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargoActionPerformed(evt);
            }
        });
        jPanel1.add(cbCargo);
        cbCargo.setBounds(50, 240, 280, 40);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimagenes/16009697.jpg"))); // NOI18N
        btnSalir.setText("Salir");
        jPanel1.add(btnSalir);
        btnSalir.setBounds(750, 390, 160, 60);

        lblherramientas.setBackground(new java.awt.Color(255, 255, 255));
        lblherramientas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblherramientas);
        lblherramientas.setBounds(50, 370, 890, 100);

        tblMantenimientopesonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMantenimientopesonal);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 500, 890, 180);

        TxtAsistencia.setBackground(new java.awt.Color(51, 51, 51));
        TxtAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        TxtAsistencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ASISTENCIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.add(TxtAsistencia);
        TxtAsistencia.setBounds(650, 240, 280, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimagenes/2560x1440-Fondo-de-pantalla-de-gris-negro-sombra-superficie-linea.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-480, 0, 1600, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCargoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtAsistencia;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombres;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblherramientas;
    private javax.swing.JTable tblMantenimientopesonal;
    private javax.swing.JTextField txtDNI;
    // End of variables declaration//GEN-END:variables
}
